# Generated by Django 4.2.16 on 2025-10-10 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_path', models.CharField(help_text='Path to the stored file', max_length=500)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='File MIME type', max_length=150)),
                ('file_extension', models.CharField(help_text='File extension', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description of the attachment')),
                ('org', models.CharField(default='AI', help_text='Organization name', max_length=100)),
                ('user', models.ForeignKey(help_text='User who uploaded the attachment', on_delete=django.db.models.deletion.CASCADE, related_name='blendx_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', 'created'], name='blendxcours_user_id_6e74fc_idx'), models.Index(fields=['file_type'], name='blendxcours_file_ty_6864cf_idx'), models.Index(fields=['org'], name='blendxcours_org_cff968_idx')],
            },
        ),
    ]
